### ISSUE TITLE
would it be better if Vertex doesn't consume Indentifier

### ISSUE THREAD

**Issue by AndyJado** [indradb/indradb#257] opened 2022-12-05 07:08 UTC
if I have million vertexes with same Identifier, there will be a million of .clone() happening, right?

I'm a little confused, newbee to database stuff, is it not encouraged to have a lot of same type vertexes?

**Comment by AndyJado** [comment] 2022-12-05 09:03
owuu I just saw #66, I'm planning to use the pure rust-lib, would some one guide me to contribute? it kicks me in the belly everytime I see a clone🥺

**Comment by ysimonson** [comment] 2022-12-06 03:45
The problem is that the values are frequently consumed, e.g. parts of an input query will be consumed to construct new queries. Accepting references would hide this fact, and carry performance overhead in needing to clone (rather than move.)

I do wish there were a better way though. A couple of ideas, but I could use some feedback from experienced rustaceans:

- Trait methods could accept `Cow`, and then we could accept either references or values, and only clone when actually necessary. This would be the friendliest to underlying implementations, since if/when they clone will likely vary. However, it's not great from a DX point-of-view; instead of cloning values to pass in, you'd be constructing `Cow`s which is even wordier. Also all the extra branching would carry its own overhead.
- We could accept references, but make large values within models (e.g. the string in `Identifier`) an `Arc` to minimize the cost of cloning.

**Comment by AndyJado** [comment] 2022-12-21 02:42
I guess DX shorts for 'developer experience' ? 

I've made couple stupid `derive` for `vertex` and `edge` so I don't have to leave compile time sweetness in [my project][ref], however I felt some overheads happening, can't put out with word yet..


[ref]: https://github.com/AndyJado/fiberay/blob/549ee2df4f57498075362b7608a3f37ddec7cf75/songma_derive/src/lib.rs#L5

**Comment by ysimonson** [comment] 2023-01-29 22:49
Yes that’s right, DX means developer experience in this context. This issue is resolved in the forthcoming IndraDB v4. Identifiers are now copyable, with the value being interned.

**Closed by ysimonson** 2023-01-29 22:49 UTC
Labels: enhancement, help wanted
