### ISSUE TITLE
MemoryDatastore read fail: Error: DeserializeAnyNotSupported

### ISSUE THREAD

**Issue by AndyJado** [indradb/indradb#258] opened 2022-12-10 14:14 UTC
## In a word

MemoryDatastore `read()` a db with `vertex & vertex properties` fail, same logic, rockdb works just fine

## version info

tested both on a ubunto 20.04 and a macos13.

```toml
indradb-lib = { version = "*", features = ["rocksdb-datastore"] }
serde = { version = "^1.0.57", features = ["derive"] }
serde_json = "^1.0.57"
byteorder = "^1.4.2"
lazy_static = "^1.4.0"
chrono = { version = "0.4.22", features = ["serde"] }
bincode = "^1.3.3"
tempfile = "^3.2.0"
uuid = { version = "^1.1.2", features = ["v1", "serde"] }
```
## describe

say I sync a database with `vertex_properties` empty, It can read fine, however if I insert bulk and debug the db:

```
MemoryDatastore {
    datastore: RwLock {
        data: InternalMemoryDatastore {
            vertices: {
                7bcb3d52789411ed8000000000000000: Identifier(
                    "sample",
                ),
            },
            edges: {},
            reversed_edges: {},
            vertex_properties: {
                (
                    7bcb3d52789411ed8000000000000000,
                    Identifier(
                        "idsdad",
                    ),
                ): Json(
                    Bool(true),
                ),
            },
            edge_properties: {},
            property_values: {},
        },
        poisoned: false,
        ..
    },
    path: Some(
        "image.bincode",
    ),
}
```
then write is fine, it just cannot be `read()` anymore and give the Error in issue.

**Comment by ysimonson** [comment] 2022-12-10 15:48
Is this the correct flow?

1) created a memory datastore
2) inserted one vertex
3) synced the database, it’s ok
4) bulk inserted one vertex property
5) synced again, it fails?

**Comment by AndyJado** [comment] 2022-12-10 16:57
>Is this the correct flow?

🙋: I only synced once at end of file.

## minimal code

now I did just as you describe, it fails the same. I do believe it's the `Json` type's problem
```rust
use indradb::Datastore;
use indradb::*;
use serde_json::json;

fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
    // Create an in-memory datastore
    let p = &"image.bincode";
    let datastore = MemoryDatastore::create(p)?;

    // Create a couple of vertices
    let out_v = Vertex::new(Identifier::new("product")?);
    datastore.create_vertex(&out_v)?;
    datastore.sync()?;
    let ppt_iden = Identifier::new("ppt_iden")?;
    let v_q = SpecificVertexQuery::single(out_v.id);
    //FIXME: once I insert a property
    datastore.set_vertex_properties(
        VertexPropertyQuery {
            inner: v_q.into(),
            name: ppt_iden,
        },
        json!(3),
    )?;
    datastore.sync()?;
    dbg!(&datastore);
    let db2 = MemoryDatastore::read(p)?;
    dbg!(db2);
    Ok(())
}
```

**Comment by ysimonson** [comment] 2022-12-15 15:13
I see, thanks. Looks like it's reproducible also by updating the `should_serialize` test fn:

```rust
#[cfg(feature = "test-suite")]
#[test]
fn should_serialize() {
    use super::MemoryDatastore;
    use crate::{Datastore, Identifier, SpecificVertexQuery, VertexPropertyQuery};
    use tempfile::NamedTempFile;

    let path = NamedTempFile::new().unwrap();

    let id = {
        let datastore = MemoryDatastore::create(path.path()).unwrap();
        let id = datastore.create_vertex_from_type(Identifier::new("product").unwrap()).unwrap();
        datastore.set_vertex_properties(
            VertexPropertyQuery {
                inner: SpecificVertexQuery::single(id).into(),
                name: Identifier::new("ppt_iden").unwrap(),
            },
            serde_json::Value::Bool(true),
        ).unwrap();
        datastore.sync().unwrap();
        id
    };

    let datastore = MemoryDatastore::read(path.path()).unwrap();
    assert_eq!(datastore.get_vertex_count().unwrap(), 1);
    let vertices = datastore
        .get_vertices(SpecificVertexQuery::new(vec![id]).into())
        .unwrap();
    assert_eq!(vertices.len(), 1);
    assert_eq!(vertices[0].id, id);
    assert_eq!(vertices[0].t, Identifier::new("product").unwrap());
}
```

**Comment by ysimonson** [comment] 2022-12-15 15:32
Ah, it looks like bincode and serde_json are not compatible with each other!

```rust
use serde::{Deserialize, Serialize};
use serde_json::json;

fn main() {
    let container = json!(3);
    let encoded: Vec<u8> = bincode::serialize(&container).unwrap();
    bincode::deserialize::<serde_json::Value>(&encoded[..]).unwrap();
} 
```

A little more context: https://github.com/bincode-org/bincode/issues/374

**Comment by ysimonson** [comment] 2022-12-20 16:30
I don't see a clean way around this with bincode. Instead, in #260, added functions for [de-]serializing an in-memory datastore via msgpack. For backwards compatibility, by default bincode will continue to be used, but it will throw an error when attempting to sync with properties enabled. Bincode-related constructors are now marked as deprecated, and will be removed in the next major version.

**Closed** 2022-12-20 19:03 UTC
Labels: bug, high priority
